Implement `discord.Message` objects as proxy messages
BadWolf1023/MKW-Table-Bot pull request #146
Opened 2022-06-04 20:38 UTC by camelwater

## Description

Implement `discord.Message` object as the proxy message (`InteractionUtils.create_proxy_msg()`) instead of a `discord.Object` object. This way, future additions to how we handle slash commands can be easily accommodated (eg. replying, editing, etc.).

Also, condense some error messages in the embed footer.

## Checklist

- [x] If code changes were made, they have been tested
- [ ] This PR fixes an issue
- [ ] This PR is not a code change (ie. documentation, typehinting, comments, etc.)

2022-06-05 22:47 UTC, BadWolf1023 reviewed
See comments.

2022-06-05 22:47 UTC, BadWolf1023 commented on TableBot.py
> +            command = re.sub(r"<@!?(\d{15,20})>\s*", "/", command)
What if their command was `/changeplace <@901018382810> 1 3`?

2022-06-05 22:47 UTC, BadWolf1023 commented on TableBot.py
> +            command = re.sub(r"<@!?(\d{15,20})>\s*", "/", command)
Same as above comment.

2022-06-05 22:47 UTC, BadWolf1023 commented on slash_cogs/LoungeSlashCommands.py
> +        print(ctx.value)
Should remove.

2022-06-05 22:47 UTC, BadWolf1023 commented on ErrorChecker.py
> -                        errors.append(f"{player_name} DCed and was on results. Giving {numberOfDCPtsGivenOn} total DC points (3 per missing race). ({len(race.placements)} players in room this race)")
Personally, I like the transparency of 3 per missing race. Some formats use a different number than 3, so it's good to be straight forward on how the DC points are calculated.

Speaking of which, a requested feature is a server setting to change the number of DC points given per race, and also change the number of points given to a player on the race they disconnected (traditionally is 0, but some formats call for 2).

Back to the first part of the comment, how can we be concise, yet clear on the DC points given and how they are given?

2022-06-05 22:47 UTC, BadWolf1023 commented on ErrorChecker.py
> +                    errors.append(f"{player_name} had a blank race time. Disconnected unless mkwx bug. No DC points this race - use /changeroomsize if they were not on the results of this race")
Maybe "no DC points given for this race"? Want to be clear that it is this race alone that they will not receive points; as opposed to "starting this race, not giving any DC points at all" - I know, it seems nitpicking over words on the last 2 comments - I think it's critical that what many people consider a black box gives the most clarity and transparency that it can, so there is no room for misunderstanding. Let's brainstorm these.

2022-06-05 22:47 UTC, BadWolf1023 commented on ErrorChecker.py
> -                            err_mes = f"{clean_name} is missing. Giving {war.missingRacePts} DC points per missing race. ({len(race.placements)} players in room) - Use ?dcs to fix this."
So we always give them a suggestion to fix this?

2022-06-05 22:47 UTC, BadWolf1023 commented on commands.py
> +                    while att < 3:
Let's take it down to 2. I noticed that when TinyURL fails, it often comes in batches. I don't want them to label TableBot as a bad actor by sending more requests when it already responded with a failure code.

Alternatively, we could asyncio.sleep for .75 seconds?

2022-06-05 23:00 UTC, camelwater commented on commands.py
> +                    while att < 3:
Yeah, that's a good idea.

2022-06-05 23:03 UTC, camelwater commented on Components.py
> +    async def next_suggestion(self, interaction: discord.Interaction = None):
Half of the changes are just reorganization of method locations, and the other half is fixing a ctx.response bug where the button would still be "thinking" (loading) even after being clicked.

2022-06-05 23:04 UTC, camelwater commented on ErrorChecker.py
> -                        errors.append(f"{player_name} DCed and was on results. Giving {numberOfDCPtsGivenOn} total DC points (3 per missing race). ({len(race.placements)} players in room this race)")
Yeah, I see what you mean. I think the (x per missing race) is fine.

2022-06-05 23:05 UTC, camelwater commented on ErrorChecker.py
> +                    errors.append(f"{player_name} had a blank race time. Disconnected unless mkwx bug. No DC points this race - use /changeroomsize if they were not on the results of this race")
Yep

2022-06-08 20:37 UTC, BadWolf1023 requested changes

2022-06-08 20:37 UTC, BadWolf1023 commented on ErrorChecker.py
> +                    err_mes = f"{len(race.placements)} players at start of GP. Should have {war.get_num_players()} players."
See Discord conversation.

2022-06-08 20:38 UTC, camelwater commented on common.py
> +JSON_META_FILE = f"{DATA_PATH}meta.json"
Yep

2022-06-08 20:40 UTC, camelwater commented on commands.py
> +            if roomSize == this_bot.room.races[raceNum-1]:
You’re right. That’s a mistake.

2022-06-09 01:38 UTC, merged