Record command
BadWolf1023/MKW-Table-Bot pull request #192
Opened 2023-07-04 21:53 UTC by camelwater

## Description

## Checklist

- [x] If code changes were made, they have been tested
- [ ] This PR fixes an issue
- [ ] This PR is not a code change (ie. documentation, typehinting, comments, etc.)

2023-07-05 03:20 UTC, BadWolf1023 requested changes
Please see my comments.

2023-07-05 03:20 UTC, BadWolf1023 commented on data_tracking/Data_Tracker_SQL_Query_Builder.py
> +        SELECT Place.race_id, Place.place
I did not write this query originally. It has definitely has some fine print. I ran your proposed query against an old version of our DB, and it took 1200ms to run. Here is my proposed query, which executes in 10ms. You need to tweak it for the days filter clause and is_ct clause.
```
SELECT Place.race_id, Place.place
FROM Place
JOIN Race USING (race_id)
JOIN Track USING (track_name)
WHERE time < 6 * 60	
AND Track.is_ct = 1
/* Insert time filter here. EG: AND Track.time_added > date('now','-7 days') */
AND Place.fc IN (
	SELECT fc
	FROM Player_FCs
	WHERE discord_id = 674737530318618664
)
```

Note: This only looks at races. It does not attempt to determine if the match was played in Lounge or not. I don't think people care if their record includes fun rooms or WWs that were tabled. If you disagree, we can add this back in, which shouldn't change the run time too much:
```
WHERE player_setup_amount == 12
{SQL_Search_Query_Builder.get_event_valid_filter()}
```

2023-07-05 03:20 UTC, BadWolf1023 commented on data_tracking/Data_Tracker_SQL_Query_Builder.py
> +        SELECT Place.race_id, Place.place
See test results here:
![image](https://github.com/BadWolf1023/MKW-Table-Bot/assets/23650362/70c88b85-920b-45b0-b035-eef26cf6e2e8)

Versus
![image](https://github.com/BadWolf1023/MKW-Table-Bot/assets/23650362/b8806781-5d39-4feb-bc0a-fa0bdd16930c)

2023-07-05 04:15 UTC, BadWolf1023 requested changes

2023-07-05 04:15 UTC, BadWolf1023 commented on data_tracking/Data_Tracker_SQL_Query_Builder.py
> +            INNER JOIN ({SQL_Search_Query_Builder.get_player_races(opponent_did, days, is_ct)}) as b
INNER JOIN doesn't know *what* you want to join on. (The original JOIN code doesn't either.)

I believe both generate a cartesian product, which is both incorrect and lengthy. 11000ms on my machine.

I suggest this instead:
```
FROM ({SQL_Search_Query_Builder.get_player_races(player_did, days, is_ct)}) as a 
INNER JOIN ({SQL_Search_Query_Builder.get_player_races(opponent_did, days, is_ct)}) as b
USING (race_id)
```

2023-07-05 04:23 UTC, BadWolf1023 commented on data_tracking/Data_Tracker_SQL_Query_Builder.py
> +            INNER JOIN ({SQL_Search_Query_Builder.get_player_races(opponent_did, days, is_ct)}) as b
I can confirm that the original code does indeed generate a cartesian product and it is not correct. This live production code? The bot currently responds in a timely manner...? It took 88 **seconds** on my machine.

2023-07-05 04:57 UTC, BadWolf1023 commented on data_tracking/Data_Tracker_SQL_Query_Builder.py
> +            INNER JOIN ({SQL_Search_Query_Builder.get_player_races(opponent_did, days, is_ct)}) as b
Sorry, I didn't see the `ON a.race_id = b.race_id` *facepalm*

2023-07-05 07:29 UTC, BadWolf1023 commented on commands.py
> +            player_did = str(UserDataProcessing.get_DiscordID_By_LoungeName(players[0]))
This is a good opportunity to use SmartTypes

2023-07-07 01:27 UTC, camelwater commented on data_tracking/Data_Tracker_SQL_Query_Builder.py
> +        SELECT Place.race_id, Place.place
I added the event filter because the time filter needs the Event table anyways. The query takes less time than before (2 sec each), but it isn't as fast compared to the one you suggested (without event validation).

2023-07-07 01:44 UTC, BadWolf1023 commented on data_tracking/Data_Tracker_SQL_Query_Builder.py
> +        SELECT Place.race_id, Place.place
I talked to people in Lounge. The event validation seems to limit the returned races more than intended. Because of this, people complain their records are wrong. I think we should drop the even validation.

2023-07-07 01:53 UTC, camelwater commented on data_tracking/Data_Tracker_SQL_Query_Builder.py
> +        SELECT Place.race_id, Place.place
The time filter is still fine though, right?

2023-07-07 02:01 UTC, BadWolf1023 commented on data_tracking/Data_Tracker_SQL_Query_Builder.py
> +        SELECT Place.race_id, Place.place
Time filter is fine. It's customizable anyway.

2023-07-07 02:58 UTC, BadWolf1023 commented on data_tracking/Data_Tracker_SQL_Query_Builder.py
> +        SELECT Place.race_id, Place.place
> 

Referring to https://github.com/BadWolf1023/MKW-Table-Bot/blob/main/data_tracking/sql_database_diagram.png

It looks like `Race` has a `time_added` column. This should work, no?

2023-07-07 04:38 UTC, camelwater commented on data_tracking/Data_Tracker_SQL_Query_Builder.py
> +        SELECT Place.race_id, Place.place
Wow, I didn't see that. Oops

2023-07-07 05:29 UTC, BadWolf1023 commented on Room.py
> +        save_state['name_changes'] = self.name_changes.copy()
https://trinket.io/python/ec732eb982

2023-07-07 05:39 UTC, BadWolf1023 commented on Room.py
> +        save_state['name_changes'] = self.name_changes.copy()
I don't see it this line changed in Files Changed anymore. My Github might be bugged. Please disregard if this is outdated.

2023-07-07 07:09 UTC, camelwater commented on Room.py
> +        save_state['name_changes'] = self.name_changes.copy()
The dict within the dict is always replaced. A new dict is always used, so deep copying wouldn't differ from shallow copying.
The name_changes dict could be redesigned where new name changes modify the nested dict object, but I just left it as it is.

2023-07-07 07:21 UTC, BadWolf1023 commented
I will try to review tomorrow. It’s late here.

2023-07-07 22:31 UTC, BadWolf1023 approved these changes
Excellent, looks solid.

2023-07-08 00:04 UTC, merged