Various Bug Fixes and unnecessary code removal episode 2 (actually works edition)
BadWolf1023/MKW-Table-Bot pull request #195
Opened 2023-07-05 02:51 UTC by Fear-MK

## Description
Fixed following open issues:
- Implemented "Squad Queue" tier from recent Lounge API update (Untested)
- Fixed Predict command and eradicated all URL shortening code (useless as tinyurl API has become unavailable) (Untested)
- Fixed list formatting issues within certain commands (Tested)
## Checklist

- [ ] If code changes were made, they have been tested
- [x] This PR fixes an issue
- [ ] This PR is not a code change (ie. documentation, typehinting, comments, etc.)

2023-07-05 03:47 UTC, BadWolf1023 requested changes
Please see my comments.

2023-07-05 03:47 UTC, BadWolf1023 commented on BadWolfBot.py
> -        URLShortener.BITLY_API_TOKEN = read_next_token(f)
Please update `private_example.txt` to comply with these new changes.

2023-07-05 03:47 UTC, BadWolf1023 commented on MogiUpdate.py
> -def create_player_json(player:Tuple[str, int, int, int], races_played=12, sub_in=False, sub_out=False, squadqueue=False):
Nice catch

2023-07-05 03:47 UTC, BadWolf1023 commented on MogiUpdate.py
Squad queue update looks like good work

2023-07-05 03:47 UTC, BadWolf1023 commented on TagAIShell.py
> +            result += '\t'*num_tabs + f"\t{playerNum}\. {playerName}\n"
No, this isn't Discord text

2023-07-05 03:47 UTC, BadWolf1023 commented on Room.py
> +            to_build += f"\t{counter}\. {UserDataProcessing.proccessed_lounge_add(player, fc, lounge_replace)}{fc_str}"
This looks buggy to me - we removed the new line and added a tab instead...? Please show screenshots of what this change looks like.

2023-07-05 03:47 UTC, BadWolf1023 commented on Race.py
> +            placementsSTR += str("\n" + str(placement))
This looks like an unintended change to our display. Please show screenshots of what this change looks like.

2023-07-05 03:47 UTC, BadWolf1023 commented on commands.py
> -
Now they can't preview the update at all. Please see #186 for exact instructions.

2023-07-05 03:47 UTC, BadWolf1023 commented on commands.py
> -
Now they can't preview the update at all. Please see https://github.com/BadWolf1023/MKW-Table-Bot/issues/186 for exact instructions.

2023-07-05 03:47 UTC, BadWolf1023 commented on logging/feedback_logs.txt
> +2021-06-27 15:49:45.099623: Bad Wolf#1024 - 706120725882470460:log I really like the mii heads! shut up
Let's keep the main repo professional (so remove).

2023-07-05 03:50 UTC, Fear-MK commented on TagAIShell.py
> +            result += '\t'*num_tabs + f"\t{playerNum}\. {playerName}\n"
Sorry must have been a bi-product of testing all sorts of random stuff and forgetting to remove

2023-07-05 03:51 UTC, Fear-MK commented on Room.py
> +            to_build += f"\t{counter}\. {UserDataProcessing.proccessed_lounge_add(player, fc, lounge_replace)}{fc_str}"
yes it does not sure what I did here, going to run this code tmw, and see what it looked like

2023-07-05 03:52 UTC, Fear-MK commented on Race.py
> +            placementsSTR += str("\n" + str(placement))
Was sent in DMs previously. It meant an ornate list, but different formatting. I commented but you said it was fine (will find original message later

2023-07-05 03:54 UTC, Fear-MK commented on commands.py
> -
Yep my mistake, I assumed there were two link boxes. Didnt check specific instructions

2023-07-06 17:42 UTC, Fear-MK commented on Race.py
> +            placementsSTR += str("\n" + str(placement))
![image](https://github.com/BadWolf1023/MKW-Table-Bot/assets/89424149/ae54080a-6e8f-4ba6-bd02-5f2fb934ce70)

2023-07-06 17:56 UTC, Fear-MK commented on logging/feedback_logs.txt
> +2021-06-27 15:49:45.099623: Bad Wolf#1024 - 706120725882470460:log I really like the mii heads! shut up
fine

2023-07-06 18:18 UTC, Fear-MK commented on BadWolfBot.py
> -        URLShortener.BITLY_API_TOKEN = read_next_token(f)
Will try if I can sync branch after next commit

2023-07-06 18:21 UTC, Fear-MK commented on Race.py
> +            placementsSTR += str("\n" + str(placement))
Will wait on confirmation that this is satisfactory

2023-07-06 20:11 UTC, camelwater commented on Race.py
> +            placementsSTR += str("\n" + str(placement))
I like the tab. It spaces out the placements from the race details

2023-07-06 20:25 UTC, Fear-MK commented on Race.py
> +            placementsSTR += str("\n" + str(placement))
> I like the tab. It spaces out the placements from the race details

the tab is what was causing peculiar format issues

2023-07-06 20:29 UTC, Fear-MK commented on Race.py
> +            placementsSTR += str("\n" + str(placement))
Gonna quickly try something, actually

2023-07-06 20:53 UTC, Fear-MK commented on Race.py
> +            placementsSTR += str("\n" + str(placement))
Command has been reverted to its original form.

2023-07-06 20:54 UTC, Fear-MK commented on commands.py
> -
Renamed Short Preview Link to Preview Link and supplied full link to field

2023-07-06 20:54 UTC, Fear-MK commented on commands.py
> -
I lied, this isnt complete, iirc

2023-07-06 22:36 UTC, BadWolf1023 requested changes
All of the old issues look good to go, however we need to change how `multiple_rxxs_used` is done as that is prone to bugs.

2023-07-06 22:36 UTC, BadWolf1023 commented on Room.py
> +        self.multiple_rxxs_used = False
Not necessary and prone to bugs if `/undo` is run. Make a new function:
```
def has_multiple_rxxs(self):
   return len(self.rLIDs) > 1
```

2023-07-06 22:36 UTC, BadWolf1023 commented on commands.py
> +                    tableWasEdited = len(this_bot.getWar().manualEdits) > 0 or len(this_bot.getRoom().dc_on_or_before) > 0 or len(this_bot.getRoom().forcedRoomSize) > 0 or this_bot.getRoom().had_posi
See other comment. Minor change.

2023-07-07 00:18 UTC, camelwater approved these changes
LGTM

2023-07-07 00:21 UTC, BadWolf1023 commented
> LGTM

still some old references of `multiple_rxxs_used`, but getting close

2023-07-07 00:22 UTC, Fear-MK commented
i did provide an update for this but idk how to merge the changes now

2023-07-07 00:27 UTC, Fear-MK commented
> i did provide an update for this but idk how to merge the changes now

there is one line that needs to be deleted entirely, it is in the merge_room_command async function in commands.py (sets a value to True just before state is saved

one reference of multiple_rxxs_used somewhere, cant remember where

2023-07-07 00:50 UTC, BadWolf1023 approved these changes
Good to go imo

2023-07-07 00:57 UTC, camelwater approved these changes

2023-07-07 00:57 UTC, merged